language: python
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
install:
  - pip install -U tox
script:
  - tox -r
env:
  - TOXENV=py27_django17
  - TOXENV=py34_django18
  - TOXENV=coverage
notifications:
  email: false
sudo: false
