language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e .
  - pip install -q -r example/requirements.txt --use-mirrors
env:
  - DJANGO=1.3.1
  - DJANGO=1.4.1
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
branches:
  only:
    - master
    - testsuite
script:
  - python setup.py test
