language: python
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py27_django14
  - TOXENV=py27_django17
  - TOXENV=py34_django17
  - TOXENV=coverage
notifications:
  email: false
