language: python
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py26_django14
  - TOXENV=py27_django16
  - TOXENV=py33_django16
  - TOXENV=py34_django16
  - TOXENV=coverage
notifications:
  email: false
