language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.5
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q PIL==1.1.7 --use-mirrors
  - pip install -q selenium==2.31 --use-mirrors
  - pip install -q -e .
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python setup.py test
